### ISSUE TITLE
Results on val set of WIDER FACE?

### ISSUE THREAD

**Issue by DuckJ** [Vishu8/WIDER-Face-Detection-using-MTCNN#1]
could you give the results on val set of WIDER FACE?

Easy Set | Medium Set | Hard Set

**Comment by v1zh3d** [comment]
![easy_set](https://user-images.githubusercontent.com/46747876/71501421-70238880-2890-11ea-8982-3f80c6ef6fc7.PNG)

Easy Set Accuracy

![medium_set](https://user-images.githubusercontent.com/46747876/71501426-76196980-2890-11ea-967d-8fb2b44df0e2.PNG)

Medium Set Accuracy

![hard_set](https://user-images.githubusercontent.com/46747876/71501431-7ade1d80-2890-11ea-9723-d9d022427c9e.PNG)

Hard Set Accuracy

**Comment by v1zh3d** [comment]
Shared the validation set outputs
